### ISSUE TITLE
【直观详解】泰勒级数 | Go Further | Stay Hungry, Stay Foolish

### ISSUE THREAD

**Issue by CharlesLiuyx** [CharlesLiuyx/BlogComment#15]
https://charlesliuyx.github.io/2018/02/16/%E3%80%90%E7%9B%B4%E8%A7%82%E8%AF%A6%E8%A7%A3%E3%80%91%E6%B3%B0%E5%8B%92%E7%BA%A7%E6%95%B0/

**Comment by congzhangzh** [comment]
朋友你的动图太生动了，怎么生成的？

**Comment by CharlesLiuyx** [comment]
@congzhangzh 在文章里面有说明，来自于[3B1B的视频](https://www.bilibili.com/video/av11251323/?from=search&seid=10355824295490802414)

**Comment by congzhangzh** [comment]
收到，谢谢
