### ISSUE TITLE
什么是信息熵、交叉熵和相对熵 | 尼孟尼克 Blog | Stay Hungry, Stay Foolish

### ISSUE THREAD

**Issue by CharlesLiuyx** [CharlesLiuyx/BlogComment#5]
https://charlesliuyx.github.io/2017/09/11/%E4%BB%80%E4%B9%88%E6%98%AF%E4%BF%A1%E6%81%AF%E7%86%B5%E3%80%81%E4%BA%A4%E5%8F%89%E7%86%B5%E5%92%8C%E7%9B%B8%E5%AF%B9%E7%86%B5/

**Comment by lance6716** [comment]
在确定性更大的概率分布情况下，用更不确定的存储策略来计算

然后接下来举例的P和Q说反了吗

**Comment by CharlesLiuyx** [comment]
@lance6716 感谢指正，已经修改
